smlua_text_utils_course_acts_replace(COURSE_BOB, (" 1  BATALLON BOB-OMB"),	("GRAN REY BOB-BOM EN LA CIMA"),	("CARRERA CON KOOPA EL VELOZ"),	("DISPARA HACIA LA ISLA EN EL CIELO"),	("BUSCA LAS 8 MONEDAS ROJAS"),	("MARIO ALADO HACIA EL CIELO"),	("DETRAS DE LA JAULA DE CHAIN CHOMP"))

smlua_text_utils_course_acts_replace(COURSE_WF, (" 2 FORTALEZA WHOMP"),	("APLASTA AL GRAN WHOMP"),	("HACIA LA CIMA DE LA FORTALEZA"),	("VUELA HACIA LA GRAN PLATAFORMA"),	("8 MONEDAS ROJAS ISLA FLOTANTE"),	("CAE EN LA ISLA ENJAULADA"),	("CHOCA CONTRA LA MURALLA"))

smlua_text_utils_course_acts_replace(COURSE_JRB, (" 3 BAHIA JOLLY ROGER"),	("SAQUEO EN EL BARCO HUNDIDO"),	("PUEDE LA ANGUILA SALIR A JUGAR?"),	("TESORO EN LA CUEVA OCEANICA"),	("MONEDAS ROJAS EN EL BARCO A FLOTE"),	("CHOCA EN EL PILAR DE PIEDRA"),	("A TRAVES DE LA CORRIENTE"))

smlua_text_utils_course_acts_replace(COURSE_CCM, (" 4 COLINA NEVADA"),	("DESLIZANDOSE A LA META"),	("PEQUENO PINGUINO PERDIDO..."),	("CARRERA CONTRA EL GRAN PINGUINO"),	("DESLIZANDOME POR 8 MONEDAS ROJAS"),	("EL MUNECO DE NIEVE PERDIO LA CABEZA"),	("ESCUELA DE SALTO PARED"))

smlua_text_utils_course_acts_replace(COURSE_BBH, (" 5 MANSION EMBOOJADA"),	("TEMPORADA DE BOOS"),	("CABALGA EL CARRUSEL BOO"),	("EL SECRETO EN LA BIBLIOTECA"),	("BUSCA LAS 8 MONEDAS ROJAS"),	("BALCON DEL GRAN BOO"),  ("OJO EN LA SALA SECRETA"))

smlua_text_utils_course_acts_replace(COURSE_HMC, (" 6 LA CUEVA LABERINTICA"),	("LA BESTIA ACUATICA EN LA CUEVA"),	("ELEVATE POR 8 MONEDAS ROJAS"),	("MARIO CABEZA-METALICA MUEVETE!"),	("ENAVEGANDO EN LA NIEBLA TOXICA"),	("UNA SWOOPER ESCAPADA!"),	("CUIDADO! ROCAS GIRATORIAS"))

smlua_text_utils_course_acts_replace(COURSE_LLL, (" 7 TIERRA VOLCANICA"),	("COCINANDO CON GRAN BULLY"),	("TRES TRISTES BULLIES"),	("8 MONEDAS ROJAS EN UN ROMPECABEZAS"),	("TRONCO GIRATORIO ARDIENTE"),	("PIES CALIENTES EN EL VOLCAN"),	("TOUR EN ELEVADOR ADENTRO DEL VOLCAN"))

smlua_text_utils_course_acts_replace(COURSE_SSL, (" 8 DUNAS MOVEDIZAS"),	("EN LOS TALONES DEL GRAN PAJARO"),	("BRILLO EN LA PUNTA PIRAMIDAL"),	("DENTRO DE UNA ANTIGUA PIRAMIDE"),	("DE PIE EN LOS 4 PILARES"),	("VOLANDO POR 8 MONEDAS ROJAS"),	("ROMPECABEZAS PIRAMIDAL"))

smlua_text_utils_course_acts_replace(COURSE_DDD, (" 9 MUELLE ATROZ"),	("A BORDO DEL SUBMARINO BOWSER"),	("COFRES CONTRA CORRIENTE"),	("MONEDAS ROJAS EN LOS POSTES"),	("DENTRO DE LA CORRIENTE"),	("EL PREMIO DE LA MANTA RAYA"),	("COLECCION DE GORRAS..."))

smlua_text_utils_course_acts_replace(COURSE_SL, (" 10 VENTISCA CONGELANTE"),	("MUNECO DE NIEVE CABEZON"),	("CONGELA AL BULLY"),	("EN EL FRIO PROFUNDO"),	("ESCAPE DEL ESTANQUE CONGELADO"),	("ENCORAZADO POR MONEDAS ROJAS"),	("ADENTRO DEL IGLU"))

smlua_text_utils_course_acts_replace(COURSE_WDW, (" 11 SEQUIAS HUMEDAS"),	("IMPACTANTES FLECHAS ELECTRICAS!"),	("LA CIMA DEL PUEBLO"),	("SECRETOS PROFUNDOS DEL CIELO"),	("ELEVADOR EXPRESS--APURATE!!"),	("VE AL PUEBLO POR MONEDAS ROJAS'"),	("CARRERA RAPIDA DENTRO DEL PUEBLO!"))

smlua_text_utils_course_acts_replace(COURSE_TTM, ("12 MONTANA ESCARPADA"),	("ESCALADA EN MONTANA"),	("MISTERIOS DEL MONO ENJAULADO"),	("HONGOS MIEDOSOS, MONEDAS ROJAS"),	("RESBALADERA MONTANOSA MISTERIOSA"),	("DETRAS DE LA CASCADA"),	("DISPARADO AL HONGO SOLITARIO"))

smlua_text_utils_course_acts_replace(COURSE_THI, ("13 LA GRAN PEQUENA ISLA"),	("ARRANCA LA PLANTA PIRANA"),	("LA CIMA DE LA GRAN ISLA"),	("REVANCHA CONTRA KOOPA EL VELOZ"),	("5 PEQUENITOS SECRETITOS"),	("LMONEDAS ROJAS DEL WIGGLER"),	("HAZ QUE WIGGLER SE RETUERZA"))

smlua_text_utils_course_acts_replace(COURSE_TTC, ("14 RELOJ TIC-TAC"),	("RUEDA HASTA LA JAULA"),	("LOS PENDULOS Y LA FOSA"),	("NECESITAS UNA MANECILLA?"),	("ENCIMA DE UN TWHOMP"),	("SINCRONIZADO CON LAS PLATAFORMAS"),	("MONEDAS ROJAS MAS ALLA DEL TIEMPO"))

smlua_text_utils_course_acts_replace(COURSE_RR, (" 15 CRUCERO ARCOIRIS"),	("PASEO ARCOIRIS"),	("LA MANSION EN EL CIELO"),	("MONEDAS REVOLVIDAS EN EL LABERINTO"),	("BALANCEO EN LA BRISA"),	("TRIANGULOS TRUCADOS!"),	("EN ALGUN LUGAR SOBRE EL ARCOIRIS"))

smlua_text_utils_secret_star_replace(COURSE_BITDW,    "   BOWSER EN LAS TINIEBLAS")
    smlua_text_utils_secret_star_replace(COURSE_BITFS,    "   BOWSER EN EL INFRAMUNDO")
    smlua_text_utils_secret_star_replace(COURSE_BITS,     "   BOWSER EN EL CIELO")
    smlua_text_utils_secret_star_replace(COURSE_PSS,      "   ELA RESBALADERA SECRETA DE LA PRINCESA")
    smlua_text_utils_secret_star_replace(COURSE_COTMC,    "   CAVERNA DE LA GORRA METALICA")
    smlua_text_utils_secret_star_replace(COURSE_TOTWC,    "   TORRE DE LA GORRA ALADA")
    smlua_text_utils_secret_star_replace(COURSE_VCUTM,    "   FOSA DE LA GORRA INVISIBLE")
    smlua_text_utils_secret_star_replace(COURSE_WMOTR,    "   MARIO ALADO SOBRE EL ARCOIRIS")
    smlua_text_utils_secret_star_replace(COURSE_SA,       "   EN EL ACUARIO SECRETO")
    
 smlua_text_utils_secret_star_replace(COURSE_CAKE_END, "")
 
 smlua_text_utils_castle_secret_stars_replace("   ESTRELLAS SECRETAS")
 
smlua_text_utils_extra_text_replace(0, "UNA DE LAS ESTRELLAS SECRETAS DEL CASTILLO!")
smlua_text_utils_extra_text_replace(1,(""))
smlua_text_utils_extra_text_replace(2,(""))
smlua_text_utils_extra_text_replace(3,(""))
smlua_text_utils_extra_text_replace(4,(""))
smlua_text_utils_extra_text_replace(5,(""))
smlua_text_utils_extra_text_replace(6,(""))
